a = int(input('Primul numar: '))
b = int(input('Al doilea numar: '))

print('Suma este:', a + b)
print('Diferenta:', a - b)
print('noroc')
print('Multiply: ', a * b)
print('Devision:', a / b)
print('Buna zinga')
print('corect')
